- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kodi
  host: !secret kodi_host 
  username: !secret kodi_username
  password: !secret kodi_password
  port: 8080
  turn_off_action:
    service: media_player.kodi_call_method
    data_template:
      entity_id: 'media_player.kodi'
      method: System.Reboot

- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 30
  show_all_controls: true
  use_custom_entity_ids: true
  use_episode_art: true
