- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
- platform: kodi
  host: !secret kodi_host 
  username: !secret kodi_username
  password: !secret kodi_password
  port: 8080
  turn_off_action: reboot
