- platform: transmission
  name: Slowdown Transmission
  host: !secret transmission_host
  username: !secret transmission_username
  password: !secret transmission_password

#- platform: hdmi

- platform: command_line
  switches:
    home_assistant_system_shutdown:
      command_off: "/usr/bin/sudo /sbin/reboot"

- platform: mqtt
  name: "Strip Cord"
  command_topic: "cmnd/sonoff/power"
  state_topic: "stat/sonoff/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: command_line
  switches:
    hyperion_service:
      command_on: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no homeassistant@192.168.0.103 'sudo systemctl start hyperion.service'"
      command_off: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no homeassistant@192.168.0.103 'hyperion-remote --color 000000 && sleep 2 && sudo systemctl stop hyperion.service'"
      friendly_name: Hyperion Service

- platform: command_line
  switches:
    shutdown_kali:
      command_on: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no hassio@192.168.0.9 'sudo /sbin/shutdown 0'"
      command_off: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no hassio@192.168.0.9 'sudo /sbin/shutdown -c'"
      friendly_name: Shut Down Kali

- platform: command_line
  switches:
    reboot_kali:
      command_on: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no hassio@192.168.0.9 'sudo /sbin/shutdown -r 0'"
      command_off: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no hassio@192.168.0.9 'sudo /sbin/shutdown -c'"
      friendly_name: Reboot Kali
